exclude: ".git|.tox|.venv"
default_install_hook_types: [pre-commit, commit-msg]
default_language_version:
  python: python3
fail_fast: true

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.10.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        always_run: true
        additional_dependencies:
          - "@arrai-innovations/commitlint-config@2.1.0"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/frnmst/md-toc
    rev: 8.2.2
    hooks:
      - id: md-toc
        args: [-p, -s1, github, -u, -l6]

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: circleci-config-validate
        stages: [pre-commit]
        files: ^.circleci/config.yml$
